export const ImgLogo = require('../assets/images/ic_logo.png')

export const Intro1 = require('../assets/images/Intro1.png')
export const Intro2 = require('../assets/images/Intro2.png')
export const Intro3 = require('../assets/images/Intro3.png')

export const BackImg = require('../assets/images/ic_back.png')
export const PhoneImg = require('../assets/images/ic_phone.png')
export const SmileImg = require('../assets/images/ic_smile.png')
export const BuildingImg = require('../assets/images/ic_building.png')
export const LocationImg = require('../assets/images/ic_location.png')
export const PinImg = require('../assets/images/ic_pin.png')

export const HomeImg = require('../assets/images/ic_home.png')
export const HomeFillImg = require('../assets/images/ic_home_fill.png')

export const FolderImg = require('../assets/images/ic_folder.png')
export const FolderFillImg = require('../assets/images/ic_folder_fill.png')

export const UserImg = require('../assets/images/ic_user.png')
export const UserFillImg = require('../assets/images/ic_user_fill.png')

export const SettingImg = require('../assets/images/ic_setting.png')
export const SettingFillImg = require('../assets/images/ic_setting_fill.png')

export const NotificationImg = require('../assets/images/ic_notification.png')
export const PrivacyImg = require('../assets/images/ic_privacy.png')
export const HelpImg = require('../assets/images/ic_help.png')
export const InfoImg = require('../assets/images/ic_info.png')
export const ShareImg = require('../assets/images/ic_share.png')
export const CallImg = require('../assets/images/ic_call.png')
export const LogoutImg = require('../assets/images/ic_logout.png')
export const CoinImg = require('../assets/images/ic_coin.png')
export const TrophyImg = require('../assets/images/ic_trophy.png')
export const NavigateImg = require('../assets/images/ic_navigate.png')
export const BigPhoneImg = require('../assets/images/ic_bigPhone.png')
export const AtImg = require('../assets/images/ic_at.png')
export const ShareBoxImg = require('../assets/images/shareImg.png')
export const InviteImg = require('../assets/images/ic_invitation.png')
export const RedeemImg = require('../assets/images/ic_redeem.png')
export const NotificationSq = require('../assets/images/ic_notification_sq.png')

export const AppLogoImg = require('../assets/images/appLogo.png')
export const ScanImg = require('../assets/images/ic_scan.png')
export const ScanImgBlack = require('../assets/images/ic_scan_black.png')
export const ScanColorImg = require('../assets/images/ic_scanColor.png')
export const TicketImg = require('../assets/images/ic_ticket.png')
export const CloseImg = require('../assets/images/ic_close.png')
export const FlashImg = require('../assets/images/ic_flash.png')
export const ScanImgOutline = require('../assets/images/ic_scan_outline.png')
export const CongratsImg = require('../assets/images/congratulation_box.png')
export const WithdrawImg = require('../assets/images/withdraw_congratulations.png')
export const Camera = require('../assets/images/ic_camera.png')

